### ISSUE TITLE
[Feature] Improved Article browsing

### ISSUE THREAD

**Issue by asiekierka** [DrDos0016/museum-of-zzt#14]
* Articles have Categories, and they can be filtered out via the Search Articles option, but I think it would be user-friendly to preface the "Articles Directory" link with a list of categories - in the style of the ZZT Comics archive.
* Adding a "Series" field, for videos/articles which are part of a series (say The NL, or Joy of ZZT).

**Comment by DrDos0016** [comment]
- https://museumofzzt.com/article/categories
- https://museumofzzt.com/series/

Done and done. I preferred to have the category listing be its own page as there are a significant number that would bury any actual articles placed below.

**Comment by asiekierka** [comment]
Thank you so much!
