### ISSUE TITLE
[Improvement] Image asset optimization

### ISSUE THREAD

**Issue by asiekierka** [DrDos0016/museum-of-zzt#15]
* As discussed, `optipng` is no longer used because palettization hurts embeds on some social media platforms. However, the `-nc` flag is sufficient to make optipng leave palettization alone (that is, non-indexed images will not become indexed). As such, I recommend running all PNGs through `optipng -o7 -strip=all -fix -nc`.
* The Museum of ZZT's logo is currently the largest asset on a new page load, taking up 130KB (or ~25% of the total bandwidth used! D:). As such, it should be special-cased: [here's a palettized, quantized version I made which should look identical perceptually but is ~90KB smaller](https://img.asie.pl/i79a).

**Comment by DrDos0016** [comment]
Functions that generate images on the site itself (file upload, a staff only tool that lists boards in a file, and a "use the current canvas" staff button for play online) now call optipng after generating the initial image. I've gotten in the habit of optimizing things on my end before upload for other static images used in articles and so on.
