### ISSUE TITLE
[Feature] Language field

### ISSUE THREAD

**Issue by asiekierka** [DrDos0016/museum-of-zzt#25]
The amount of non-English ZZT worlds isn't large, even if it has grown somewhat thanks to mine and KM's efforts. However, as KM has already started tagging languages in the "Title" field it might be a good idea to move this information to a separate field, and phase out the "Non-English" genre?

**Comment by DrDos0016** [comment]
Agreed and added.

Went through the non-english marked games and set their languages (plus a few lacking it from KM).

For now I'm leaving the genre in place until I get around to taking another crack at the upload system and add it there. In the meantime these are infrequent enough that setting them manually on publication is easy enough. Will also need to allow searching/filtering on the field
