### ISSUE TITLE
[Update] asiekierka/zeta-z2 -> "beta36, almost"

### ISSUE THREAD

**Issue by asiekierka** [DrDos0016/museum-of-zzt#29]
Note that this release, due to its addition of automatic font switching for Super ZZT, necessiates a small frontend fix: specifically, Super ZZT canvases should have a size of _640x400_ or larger, not just _640x350_.

**Comment by asiekierka** [comment]
It's pretty much identical to beta36. (And beta37, as that will only have SDL version changes.)

**Comment by DrDos0016** [comment]
Updated to beta38. If a file is marked with the "Super ZZT" detail it will use a 640x400 base canvas.
