### ISSUE TITLE
[Improvement] Require choosing date explicitly

### ISSUE THREAD

**Issue by asiekierka** [DrDos0016/museum-of-zzt#36]
A recent upload ("bloomy") seems to be timestamped for today, including the text file, but has the date marked as "Unknown" - presumably because the field was not populated by the uploader.

A better route would be to require explicitly selecting between an "Unknown" radio option and setting a date, with the default date being today (after all, archival is done by a small circle of people compared to "anyone willing to try ZZT").

**Comment by DrDos0016** [comment]
I've adjusted that world's release date, and adjusted the form to default to today with an "Unknown" button next to the "Today" button. This will go live in a day or two.
