### ISSUE TITLE
[Renderer/Viewer] Do not render statless objects as smilies by default

### ISSUE THREAD

**Issue by TheGreenHerring** [DrDos0016/museum-of-zzt#38]
The Museum of ZZT board renderer currently [displays objects without stats as character 2, a filled-in smiley](https://github.com/DrDos0016/museum-of-zzt/blob/master/museum_site/static/js/elements.js#L229-L233), presumably inspired by KevEdit. However, this is *not* the rendering behavior in ZZT, either in-game or in the editor. In ZZT, they are displayed as character 32, the space character, and thus invisible except for their background color. This is because [they are not assigned a specific character by the program](https://github.com/asiekierka/reconstruction-of-zzt/blob/master/SRC/ELEMENTS.PAS#L1928-L1938), [instead using parameter 1 / P1](https://github.com/asiekierka/reconstruction-of-zzt/blob/master/SRC/ELEMENTS.PAS#L949-L952). Without a P1 to set their character, they are given [the character specified in the element template, which is character 32](https://github.com/asiekierka/reconstruction-of-zzt/blob/master/SRC/ELEMENTS.PAS#L1518-L1524).

Versions of *Cyber Purge* since v1.15 use a compression method I recently discovered, in which filling the blank space between an object and a differing tile with non-statted objects of the same color as the statted one saves 3 bytes in the RLE tile data, which will add up to noticeable savings if used on an object-heavy board. This made remarkable savings on the game's object-heavy art boards in particular. However, the side effect is that due to how statless objects are currently displayed in the Viewer, the Viewer now renders *Cyber Purge*'s art boards as [covered in smiley faces that don't appear in-game](https://museumofzzt.com/file/c/cyberprg/?file=CYBERPRG.ZZT&board=39). Besides this not accurately representing how the boards look in-game or in the ZZT editor, this limits the application of this compression trick related to any world file intended to be examined in the Museum file viewer (a la PogeSoft's recent art worlds), as any such world file using the trick will be plastered with smilies where none actually exist. This behavior may also result in an inaccurate smiley-covered render being used for any board using the trick that is posted by the Worlds of ZZT bot in the future.

My request is that objects without stats should be rendered by default as space characters, as they are in-game. The KevEdit-style smiley display should instead be made a "style" option in the Prefs. menu like the options that already exist for Monitors and Board Edges. This way, not only are the statless objects rendered accurately, but the user has the option, as with Monitors and Board Edges, to make them visible at their discretion.

**Comment by DrDos0016** [comment]
Added this for the default renderer. (The code is a disaster and the file viewer is in desperate need of a full rewrite.) It won't go live until the next push which should be in the next few days due to other work that I'd rather push all at once.

**Comment by TheGreenHerring** [comment]
No problem! 👍 Thank you for the prompt response! 😀
